/**
 * academicflow-workspace 私库骨架
 * -------------------------------------------------
 * 依据 v0.2.5 §7.1.1 定义的完整清单（12 项），首次 onboarding 时一次 commit 全部写入。
 */

export interface SkeletonFile {
  path: string
  content: string
}

const README_MD = `# academicflow-workspace

这是 [AcademicFlow](https://nikki-su.github.io/AcademicFlow/) 的**个人工作区**，
由 AcademicFlow 首次登录时自动初始化。

- **归属**：仅仓库所有者可读写，私库
- **License**：数据主权归仓库所有者所有
- **管理方式**：请通过 AcademicFlow 客户端读写，不建议直接编辑 GitHub Web UI

## 目录

- \`literatures/literatures.csv\` — 文献库（一级+二级共表）
- \`vocabulary/vocabulary.csv\` — 词汇本（SM-2 间隔重复）
- \`sentences/sentences.csv\` — 长难句本
- \`translation_practice/translation_practice.csv\` — 翻译练习本
- \`keyword_groups/keyword_groups.csv\` — 追踪用关键词组
- \`textbooks/textbooks.csv\` — 课本索引
- \`projects/projects.csv\` — 项目索引
- \`settings/global.md\` — 全局设置
- \`templates/journals/_sample-generic/\` — 期刊样板
- \`templates/citations/_sample-generic.csl\` — 引用样式样板
- \`.github/workflows/daily-tracking.yml\` — 每日追踪

---

*Powered by AcademicFlow · AGPL-3.0-or-later*
`

const SETTINGS_GLOBAL_MD = `# 全局设置

## 语言
- language_mode: cn

## AI 服务
- ai1_provider: 
- ai1_model: 
- ai2_provider: 
- ai2_model: 

## PDF 处理
- pdf_retention_days: 30

## 追踪
- daily_push_time: 08:00
- push_channels: inbox

## 词典
- dict_sources: freedict, wiktionary

## 编辑器
- editor_theme: light

---

*Auto-generated by AcademicFlow onboarding.*
`

const SAMPLE_JOURNAL_META = `# 期刊元信息

name: Generic Journal
issn: 
font_size: 12pt
font_family: 
image_specs: 
citation_style: _sample-generic
`

const SAMPLE_JOURNAL_COVER_LETTER = `# Cover Letter

Dear Editor,

We are submitting our manuscript entitled "{title}" for consideration for publication in {journal_name}.

{abstract}

Sincerely,

{authors}
`

const SAMPLE_JOURNAL_TEMPLATE = `\\documentclass{article}
\\usepackage{amsmath,amssymb}
\\usepackage{graphicx}
\\usepackage{hyperref}

\\title{\\LaTeX 模板样板}
\\author{Author}
\\date{}

\\begin{document}

\\maketitle

\\begin{abstract}
摘要内容。
\\end{abstract}

\\section{引言}
正文内容。

\\begin{thebibliography}{99}
\\bibitem{ref1} 参考文献。
\\end{thebibliography}

\\end{document}
`

const SAMPLE_CSL = `<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" default-locale="en-US">
  <info>
    <title>Generic Sample Style</title>
    <id>http://academicflow.local/sample-generic</id>
    <link href="http://academicflow.local/sample-generic" rel="self"/>
    <category citation-format="author-date"/>
    <summary>AcademicFlow onboarding placeholder. Replace with your journal-specific CSL.</summary>
    <updated>2026-07-13T00:00:00+08:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA 3.0</rights>
  </info>
  <citation>
    <layout><text variable="citation-label"/></layout>
  </citation>
  <bibliography>
    <layout><text variable="title"/></layout>
  </bibliography>
</style>
`

const DAILY_TRACKING_YML = `# AcademicFlow daily tracking workflow
name: Daily Tracking

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Daily tracking script will be implemented in M8/M9."
`

const MONTHLY_CLEANUP_YML = `# AcademicFlow monthly PDF cleanup workflow
# 每月1日自动清理一个月前上传的PDF文件，仅保留Markdown
name: Monthly PDF Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup old PDFs
        run: |
          echo "=== AcademicFlow PDF Monthly Cleanup ==="
          echo "Looking for PDFs older than 30 days..."
          
          # 查找 literatures 和 textbooks 目录下超过30天的PDF
          find literatures textbooks -name "*.pdf" -type f -mtime +30 2>/dev/null | while read -r pdf; do
            if [ -f "$pdf" ]; then
              # 检查对应的Markdown是否存在
              md_file="\${pdf%.pdf}.md"
              md_dir="\${pdf%.pdf}"
              
              if [ -f "$md_file" ] || [ -d "$md_dir" ]; then
                echo "Removing old PDF: $pdf"
                git rm "$pdf"
              else
                echo "Keeping $pdf (no Markdown counterpart found)"
              fi
            fi
          done
          
          echo "Cleanup complete."

      - name: Commit and push if changes
        run: |
          git config user.name "academicflow-bot"
          git config user.email "bot@academicflow.local"
          
          if git diff --cached --quiet; then
            echo "No old PDFs to remove."
          else
            git commit -m "chore: monthly cleanup - remove PDFs older than 30 days"
            git push
            echo "Cleanup committed and pushed."
          fi
`

/** CSV 表头（严格按照 spec §4.1-4.7） */
const CSV_HEADERS = {
  literatures: 'doi,title,journal,year,authors,keywords,abstract_en,abstract_cn,tier,has_graphical_abstract,added_at,pdf_added_at,source,tracking_group',
  vocabulary: 'word_en,word_cn,definition_cn,definition_en,example_context,source_doi,status,added_at,last_review,review_count,sm2_interval,sm2_ease',
  sentences: 'id,sentence_en,sentence_cn,ai_reference_cn,source_doi,status,added_at,last_review,review_count,sm2_interval,sm2_ease',
  translation_practice: 'id,original_text,source_doi,latest_user_translation,latest_ai_feedback,latest_error_words,status,added_at,last_practice,practice_count',
  keyword_groups: 'group_id,group_name,expression,enabled,translate_abstract,created_at',
  textbooks: 'textbook_id,title,author,edition,pages,added_at,scope,chapters,included_chapters',
  projects: 'project_id,title,target_journal,textbook_refs,status,created_at,updated_at',
} as const

export const WORKSPACE_SKELETON: SkeletonFile[] = [
  { path: 'README.md', content: README_MD },
  { path: 'settings/global.md', content: SETTINGS_GLOBAL_MD },

  { path: 'literatures/literatures.csv', content: CSV_HEADERS.literatures + '\n' },
  { path: 'vocabulary/vocabulary.csv', content: CSV_HEADERS.vocabulary + '\n' },
  { path: 'sentences/sentences.csv', content: CSV_HEADERS.sentences + '\n' },
  { path: 'translation_practice/translation_practice.csv', content: CSV_HEADERS.translation_practice + '\n' },
  { path: 'keyword_groups/keyword_groups.csv', content: CSV_HEADERS.keyword_groups + '\n' },
  { path: 'textbooks/textbooks.csv', content: CSV_HEADERS.textbooks + '\n' },
  { path: 'projects/projects.csv', content: CSV_HEADERS.projects + '\n' },

  { path: 'templates/journals/_sample-generic/meta.md', content: SAMPLE_JOURNAL_META },
  { path: 'templates/journals/_sample-generic/template.tex', content: SAMPLE_JOURNAL_TEMPLATE },
  { path: 'templates/journals/_sample-generic/cover-letter.md.tpl', content: SAMPLE_JOURNAL_COVER_LETTER },
  { path: 'templates/citations/_sample-generic.csl', content: SAMPLE_CSL },

  { path: '.github/workflows/daily-tracking.yml', content: DAILY_TRACKING_YML },
  { path: '.github/workflows/monthly-cleanup.yml', content: MONTHLY_CLEANUP_YML },
]

export const DEFAULT_WORKSPACE_REPO_NAME = 'academicflow-workspace'

export const WORKSPACE_REPO_DESCRIPTION =
  'AcademicFlow 个人工作区（自动生成，请勿手动删除）'

export const INITIAL_COMMIT_MESSAGE =
  'chore: initialize AcademicFlow workspace skeleton'
