/**
 * academicflow-workspace 私库骨架
 * -------------------------------------------------
 * 依据 v0.2.5 §7.1.1 定义的完整清单（12 项），首次 onboarding 时一次 commit 全部写入。
 *
 * ⚠️ M2 阶段所有 CSV 只带表头（表头是最小可用集，M4/M5 时再扩展）；
 *    workflow 也只是占位（M9/M10 才实装追踪脚本）。
 */

/** 单个骨架文件条目 */
export interface SkeletonFile {
  path: string
  content: string
}

/** README 顶层库说明 */
const README_MD = `# academicflow-workspace

这是 [AcademicFlow](https://nikki-su.github.io/AcademicFlow/) 的**个人工作区**，
由 AcademicFlow 首次登录时自动初始化。

- **归属**：仅仓库所有者可读写，私库
- **License**：数据主权归仓库所有者所有
- **管理方式**：请通过 AcademicFlow 客户端读写，不建议直接编辑 GitHub Web UI
  （直接编辑不会破坏数据，但可能导致 CSV 结构不一致）

## 目录

- \`literatures/literatures.csv\` — 文献库
- \`vocabulary/vocabulary.csv\` — 词典
- \`sentences/sentences.csv\` — 例句库
- \`translation_practice/translation_practice.csv\` — 翻译练习
- \`keyword_groups/keyword_groups.csv\` — 关键词组
- \`textbooks/textbooks.csv\` — 教材
- \`projects/projects.csv\` — 项目
- \`settings/global.md\` — 默认配置
- \`templates/\` — 期刊/引用样板
- \`.github/workflows/daily-tracking.yml\` — 追踪脚本（后续里程碑实装）

---

*Powered by AcademicFlow · AGPL-3.0-or-later*
`

/** 默认配置说明（M3 起会写实际字段进来） */
const SETTINGS_GLOBAL_MD = `# Global Settings

M3 里程碑之后，AcademicFlow 会把用户的偏好配置（AI 模型选择、词典等）落到本文件。
M2 阶段这里只是占位。

---

*Auto-generated by AcademicFlow onboarding.*
`

/** 期刊样板占位 */
const SAMPLE_JOURNAL_README = `# _sample-generic 期刊样板

M4 起会填充实际的样板结构（元数据、citation style 引用等）。
`

/** CSL 样板占位（有效但极简的 CSL 1.0.2） */
const SAMPLE_CSL = `<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" default-locale="en-US">
  <info>
    <title>Generic Sample Style</title>
    <id>http://academicflow.local/sample-generic</id>
    <link href="http://academicflow.local/sample-generic" rel="self"/>
    <category citation-format="author-date"/>
    <summary>AcademicFlow onboarding placeholder. Replace with your journal-specific CSL.</summary>
    <updated>2026-07-13T00:00:00+08:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA 3.0</rights>
  </info>
  <citation>
    <layout><text variable="citation-label"/></layout>
  </citation>
  <bibliography>
    <layout><text variable="title"/></layout>
  </bibliography>
</style>
`

/** GitHub Actions workflow 占位（M9/M10 实装）*/
const DAILY_TRACKING_YML = `# AcademicFlow daily tracking workflow (占位)
# M9/M10 里程碑会实装真正的追踪逻辑；本文件先占位。
name: Daily Tracking (placeholder)

on:
  # 默认禁用，避免占用 Actions 配额
  workflow_dispatch:
  # schedule:
  #   - cron: '0 22 * * *'  # UTC 22:00 = 北京时间 06:00

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "This workflow is a placeholder installed by AcademicFlow onboarding (M2). It will be replaced in M9/M10."
`

/** CSV 表头（v0.2.5 未详细定义，采用最小可用集，M4/M5 扩展） */
const CSV_HEADERS = {
  literatures:
    'doi,title,authors,year,journal,added_at,updated_at,tags,notes_id',
  vocabulary: 'word_id,word,meaning,context,source_doi,added_at',
  sentences: 'sentence_id,content,translation,source_doi,added_at',
  translation_practice:
    'practice_id,original,translation,source_doi,difficulty,added_at',
  keyword_groups: 'group_id,group_name,keywords,created_at',
  textbooks: 'textbook_id,title,author,publisher,year,notes,added_at',
  projects: 'project_id,name,description,status,created_at,updated_at',
} as const

/**
 * 完整骨架清单（12 个文件）
 * 顺序不重要——GitHub Git Data API 一次 commit 处理所有。
 */
export const WORKSPACE_SKELETON: SkeletonFile[] = [
  // Markdown 说明（2）
  { path: 'README.md', content: README_MD },
  { path: 'settings/global.md', content: SETTINGS_GLOBAL_MD },

  // CSV 表头（7）
  {
    path: 'literatures/literatures.csv',
    content: CSV_HEADERS.literatures + '\n',
  },
  {
    path: 'vocabulary/vocabulary.csv',
    content: CSV_HEADERS.vocabulary + '\n',
  },
  { path: 'sentences/sentences.csv', content: CSV_HEADERS.sentences + '\n' },
  {
    path: 'translation_practice/translation_practice.csv',
    content: CSV_HEADERS.translation_practice + '\n',
  },
  {
    path: 'keyword_groups/keyword_groups.csv',
    content: CSV_HEADERS.keyword_groups + '\n',
  },
  { path: 'textbooks/textbooks.csv', content: CSV_HEADERS.textbooks + '\n' },
  { path: 'projects/projects.csv', content: CSV_HEADERS.projects + '\n' },

  // 样板（2）
  {
    path: 'templates/journals/_sample-generic/README.md',
    content: SAMPLE_JOURNAL_README,
  },
  { path: 'templates/citations/_sample-generic.csl', content: SAMPLE_CSL },

  // Workflow 占位（1）
  { path: '.github/workflows/daily-tracking.yml', content: DAILY_TRACKING_YML },
]

/** 默认私库名（v0.3 §2.3） */
export const DEFAULT_WORKSPACE_REPO_NAME = 'academicflow-workspace'

/** 私库描述 */
export const WORKSPACE_REPO_DESCRIPTION =
  'AcademicFlow 个人工作区（自动生成，请勿手动删除）'

/** 首次 commit message */
export const INITIAL_COMMIT_MESSAGE =
  'chore: initialize AcademicFlow workspace skeleton (M2)'
